version: '3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=my-password
      - MYSQL_DATABASE=inventoryiq_db
    networks:
      - laravel-mysql-network

  inventoryiq-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: inventoryiq-be-docker:latest
    container_name: inventoryiq-be-container
    volumes:
      - ./server:/usr/src/app
    restart: unless-stopped
    ports:
       - "8000:8000"
    depends_on:
       - db
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      DB_DATABASE: inventoryiq_db
      DB_PASSWORD: my-password
      DB_USER: my-user
      DB_HOST: mysqldb
      DB_PORT: 3306
    networks:
       - laravel-mysql-network

  inventoryiq-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: inventoryiq-fe-docker:latest
    container_name: inventoryiq-fe-container
    volumes:
      - ./client:/usr/src/app
    restart: unless-stopped
    ports:
     - "3000:3000"
    depends_on:
      - inventoryiq-backend
    networks:
      - laravel-mysql-network


networks:
  laravel-mysql-network:
    driver: bridge