export const REQUEST_UPDATE = 'REQUEST_UPDATE';
export const UPDATE_FORM = 'UPDATE_FORM';
export const REQUEST_RESET = 'RESET_FORM';
export const REQUEST_FETCH_START = 'FETCH_DATA_START';
export const REQUEST_FETCH_SUCCESS = 'FETCH_DATA_SUCCESS';
export const REQUEST_FETCH_ERROR = 'FETCH_DATA_ERROR';
export const REQUEST_SUBMIT = 'FORM_SUBMIT';